# ===========================
# Netlify Configuration File
# For React + Vite Project
# ===========================

[build]
  command = "npm run build"
  publish = "dist"

  # Optional: if your React app is inside a subfolder (like "acceleott-mueller"),
  # uncomment the next line and adjust:
  # base = "acceleott-mueller"

[build.environment]
  # ✅ Ensure devDependencies (like Vite) are installed
  NODE_ENV = "development"
  NPM_CONFIG_PRODUCTION = "false"

  # ✅ Optional: specify Node version (recommended by Netlify)
  NODE_VERSION = "20"

  # ✅ Avoid secret scanner false positives in node_modules and dist
  SECRETS_SCAN_OMIT_PATHS = "node_modules/**,dist/**"

  # ✅ (Optional) If secret scan still blocks builds, uncomment this:
  # SECRETS_SCAN_ENABLED = "false"

# ===========================
# Redirects for React Router
# ===========================
# Ensures React single-page app works on refresh / deep links
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ===========================
# Optional: Custom headers
# ===========================
# Improves caching and security
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
